### ISSUE TITLE
No logical combination of endpoint handlers

### ISSUE THREAD

**Issue by cheddar** [tidepool-org/dummy-api#3]
Looking over the example server js thing, everything seemed nice to me except that each of the endpoint "handler" methods gets registered individually on the server object.  This is going to be a maintenance pain point in the future as it will be pretty hard to know what methods are registered and which ones aren't for each endpoint.

I'd like to suggest that we adopt a convention of building "bundled" handler groupings which register themselves with the server.  I apologize that I'm not completely up on how people describe this stuff in JS, so my description might sound a lot like Java, but hopefully someone can help translate it.

My thought is that we have some "object"  with a well-known function "register(base, server)"

This method is in charge of registering all of its handlers at the given base path.

It would essentially look something like

``` javascript
function(base, server) {
  server.get(base, getFn);
  server.put(base, putFn);
  return server;
}
```

And then in the "main" startup script, we would essentially do something like

``` javascript
new MyHttpHandler().register("/tide/api/pool", server);
```

What do you think?

**Comment by kentquirk** [comment]
I believe I understand your comment -- I think you're essentially saying that you'd rather see all the APIs for a given collection of related functions to be registered together so that it's obvious what the shape of the API is.

I think this is interesting; it seems to be a common issue to many of these frameworks. They essentially treat each endpoint as completely separate.

We could easily have a thin wrapper around express (or whatever framework we use) to do what you're talking about.

Another option is to use a coding convention without a wrapper -- say, for example, that we don't do:

```
server.get('/a/b/c', function () { });
```

Instead, we'd always define the handle function separately, and then group together all the definitions in one block. You could take it further by saying that each major path component of the URL should be in a separate file.
